### ISSUE TITLE
Create Github pages

### ISSUE THREAD

**Issue by RudraOp9** [patatetom/jop#1]
To enhance the accessibility of the project, creating an GitHub Pages website for the repo.

**Comment by patatetom** [comment]
why not, but I've never done it and need to see how it works...

**Comment by RudraOp9** [comment]
> I've never done it 

That's really very easy , you just need index.html file on root of the repository and had to tweek some settings.
This [article could help.](https://www.geeksforgeeks.org/how-to-host-a-website-on-github-for-free/)

**Comment by patatetom** [comment]
@RudraOp9 thank you very much for the help 👍

**Comment by patatetom** [comment]
https://patatetom.github.io/jop/

**Comment by RudraOp9** [comment]
Include or link the jop.html in the index.html so that user can directly open/ use the service instead of deploying in their own machine.

**Comment by patatetom** [comment]
why not, but one of the objectives is to be autonomous, to be installed locally so as not to be _altered_.
I'd also add to be independent of the proper functioning of GitHub pages.
